serval/serval-mesh

- Cargo.lock
- Cargo.toml
- castaway/Cargo.toml
- castaway/src/api.rs
- serval-agent/Cargo.toml
- serval-agent/src/api/jobs.rs
- serval-agent/src/api/mod.rs
- serval-agent/src/api/storage.rs
- serval-agent/src/main.rs
- utils/Cargo.toml
- utils/src/blobs.rs
- utils/src/errors.rs
- utils/src/lib.rs
It's now in utils::blobs. The API is `store()`, `get_stream()`, and `get_bytes()`. Made castaway use the library, which reduced it to pure http setup and response-building.
I took castaway's endpoints and copied them wholesale into serval-agent. The agent's versions of the endpoints are `GET /blobs/:id` and `PUT /blobs` because everybody writes http endpoint names differently and I pluralize the nouns. This is not meaningful, to be clear.
MORE EXCITINGLY, serval-agent also got a `GET /run/:blob_id` endpoint which probably really shouldn't be a GET but I'm making this PR fast instead of fixing that. This runs a stored binary! No input yet, because again, PRing for discussion first, and I think that requires a little thoughtful design first.
> The content-addressed storage is now a tiny lib.

- Cargo.lock
- castaway/src/api.rs
- pounce/Cargo.toml
- pounce/src/main.rs
- serval-agent/src/api/storage.rs
- serval-agent/src/main.rs
- utils/src/blobs.rs
Sending a HEAD request to the blob retrieval endpoint now gives you a succinct way of discovering whether a given blob has been stored before or not: 200 if it has, 404 if it hasn't. This lets us avoid sending a blob up to the storage system when it's already been stored.
I also added a few minor niceties to pounce while working on this:
- default to using the filename of the wasm binary rather than "unnamed"
- show the size of the binary + input payload in the output so people aren't surprised when big requests are slow to start (my 37+ MB object detection demo takes a solid 5–10 seconds, at least)
> Respond to HEAD requests to /blobs/:addr

- serval-agent/src/api/mod.rs
- serval-agent/src/api/storage.rs
- serval-agent/src/main.rs
This adds a new middleware function that looks at the path of the incoming request and rejects any under the `/storage/` namespace if we are running with storage disabled.
In the not-so-distant future, this middleware should instead proxy the request to a node that is advertising the `serval_storage` role. I will begin working on that in a follow-up branch.
> Introduce proxy_unavailable_services middleware

- Cargo.lock
- agent/src/api/storage.rs
- storage/src/api.rs
- utils/Cargo.toml
- utils/src/errors.rs
This cleans up a lot of the http machinery, at the expense of some specific logging. The logging does include the error text, so we can improve that if we want the details back.
> Implement IntoResponse for ServalError

- Cargo.lock
- Cargo.toml
- agent/Cargo.toml
- agent/src/api/mod.rs
- agent/src/api/proxy.rs
- agent/src/main.rs
- cli/Cargo.toml
- cli/src/main.rs
- utils/Cargo.toml
- utils/src/errors.rs
- utils/src/futures.rs
- utils/src/lib.rs
- utils/src/mdns.rs
This expands the `proxy_unavailable_services` stub that we added earlier in the week to actually implement proxying, rather than returning a 503 error. When we get a request under the `/storage/` namespace, we now use mdns to look for a node advertising the `_serval_storage` role, forward a copy of the request to them, and pass the result back. With a handful of exceptions, all of the headers from the original are passed through unchanged, so non-trivial requests that make use of things like cookies should theoretically Just Work™.
There's no retry logic if things don't work for whatever reason, but I think that's ok (especially at this stage). If anything goes wrong trying to proxy the request to another node, it's surfaced to the original requestor as a [503 (service …
> Proxy storage requests to another node if we aren't in the storage role

- agent/src/api/mod.rs
- agent/src/api/v1/jobs.rs
- agent/src/api/v1/mod.rs
- agent/src/api/v1/proxy.rs
- agent/src/api/v1/storage.rs
- agent/src/main.rs
- agent/src/structures/mod.rs
- cli/src/main.rs
Did this in the cli, the endpoint uris, and the rust modules. Doing this any later in development will only get more annoying, so now is the time.
> Namespace all endpoints as /v1

- Cargo.lock
- Cargo.toml
- engine/Cargo.toml
- engine/src/lib.rs
- test-runner/Cargo.toml
This moves wasmtime and wasmtime-wasi up to the workspace-level Cargo.toml and bumps the version from 3.0.1 → 5.0.
I did this because I thought I needed something from it, but it turns out I do not. However, it's good to stay on the treadmill for core libraries like this.
> Wasmtime upgrade

- agent/src/main.rs
- agent/src/structures/mod.rs
- queue/src/api/mod.rs
- utils/src/networking.rs
This should solve our "address in use" race condition when spinning up several agents in rapid succession.
> agent - when using a randomly-selected port number, keep trying if binding fails

- engine/src/lib.rs
- engine/src/runtime/helpers.rs
- engine/src/runtime/mod.rs
This branch starts to lay the groundwork for our SDK by doing two things:
1. It sets up a module structure to contain the functions we want to expose to guests running on a Serval agent. Previously, this was just a closure in ServalEngine that exposed a simple "add two numbers" function. Now it is it's own module, along with some helpers for exchanging data between the host and guest environments.
2. It implements _most of_ what we need to let jobs [invoke capabilities](https://www.notion.so/srvl/Jobs-brain-dump-a3078a047c6944959f193afca74c6d17#06af4a7a95f04957b3d5fb3737c20b75). I plan on actually implementing a capability (and the mechanisms required to load it off disk) as my next project.
You can [find the SDK here](https://github.com/servals/sdk), as well as [a sample job that uses it …
> Initial work toward an SDK

- engine/src/runtime/mod.rs
I went down the rabbit hole of converting everything to use i64, rather than u32, in anticipation of 64-bit WASM workloads, but I decided to back that out since AFAIK no one is actually building anything with 64-bit WASM right now—and at the very least, I certainly am not, and making speculative code changes is never a great idea. That work lived and died over in #32.
This branch has a much smaller scope: it switches `invoke_capability` from using an u32 to an i32, which gives us the ability to signal different error conditions with different negative values. Easy.
> Use i32 rather than u32 for guest/host interop

- Cargo.lock
- agent/Cargo.toml
- agent/src/api/v1/jobs.rs
- agent/src/main.rs
- agent/src/structures/mod.rs
- engine/Cargo.toml
- engine/src/lib.rs
- engine/src/runtime/mod.rs
- test-runner/src/main.rs
The small news here is renaming “capabilities” to “extensions” per our [discussion in Slack](https://serval.slack.com/archives/C04BKH1J31S/p1675098898015979?thread_ts=1674764493.574109&cid=C04BKH1J31S). 🥱 
The big news here is support for WASM extensions. If you start the agent up with an `EXTENSIONS_PATH` environment variable set, it will enumerate all of the .wasm files in that directory and make them available as imports to all jobs that run on this node. Once we have the job queue implemented, nodes should send a list of all of their extensions to the job claim endpoint, manifests should include a list of extensions they require, and the job queue should only send jobs to nodes that have all of the required extensions.
What happens if a job requires something that doesn't exist? Well, …
> SDK name changes and support for WASM extensions

- Cargo.lock
- Cargo.toml
- agent/Cargo.toml
- agent/src/api/v1/jobs.rs
- agent/src/api/v1/storage.rs
- agent/src/main.rs
- agent/src/structures/mod.rs
- cli/Cargo.toml
- cli/src/main.rs
- engine/Cargo.toml
- justfile
- utils/Cargo.toml
- utils/src/blobs.rs
- utils/src/errors.rs
- utils/src/structs.rs
This PR reworks the agent API and the cli to support a new concept of a "manifest". This is a toml specification of a WASM job type. It includes a name, a namespace, a path to a binary, and some human-readable descriptions.
Here's an example manifest:
```toml
name = "loudify"
namespace = "sh.serval"
binary = "../../wasm-samples/build/loudify.wasm"
version = "1"
description = "SHOUT SHOUT LET IT ALL OUT"
required_extensions = ["birdfeeder"]
```
Once a WASM manifest + executable has been stored in the system, you can execute that wasm using the
name in the manifest: `pounce run sh.serval.loudify inputfile.txt`
The local blob storage has been reimplemented to use the [cacache](https://lib.rs/crates/cacache)
crate. This is a content-adddressable store that *also* allows lookup of items by …
> Introduce the concept of a WASM manifest; use cacache for local storage

- Cargo.lock
- agent/src/api/v1/proxy.rs
- agent/src/main.rs
- agent/src/structures/mod.rs
- engine/Cargo.toml
- engine/src/lib.rs
First and most embarrassingly of all, this fixes `proxy_unavailable_services` to actually include the body of the outermost request when proxying to another node. I am not sure how I noticed that this wasn't working. 😮‍💨
Secondly, this introduces the ability to proxy requests in the `/v1/jobs/` namespace to nodes advertising the `_serval_runner` role.
Finally, this adds a `RUNNER_ROLE` environment variable that controls whether a given instance should run jobs or proxy them elsewhere. The default is "auto", which enables job running if and only if the current platform is supported by wasmtime's cranelift code generator. This is in support of an observation that @jkbecker made about his Raspberry Pi Zero, which is a 32-bit ARM machine and is not supported by cranelift.
> Fix request proxying, introducing RUNNER_ROLE

- Cargo.lock
- agent/Cargo.toml
- agent/src/api/v1/jobs.rs
- agent/src/api/v1/proxy.rs
- agent/src/api/v1/storage.rs
- agent/src/main.rs
- agent/src/structures/mod.rs
And removed the hacky runtime state tracking. The axum app state object is now much slimmer, and we can lose the mutex around it.
The cell we're sticking the blob store into is a leverage point where we can add some indirection later if we want to.
> Moved the storage global into a once_cell

- Cargo.lock
- Cargo.toml
- agent/src/api/mod.rs
- agent/src/api/v1/jobs.rs
- agent/src/api/v1/mod.rs
- agent/src/api/v1/proxy.rs
- agent/src/api/v1/storage.rs
- agent/src/main.rs
- agent/src/structures/mod.rs
- cli/Cargo.toml
- deny.toml
Each`v1` api submodule now exports `mount()` and `mount_proxy()` as the functions to call to mount all their routes. This corrals all knowledge of exact endpoint paths to the modules, so the details of the path are no longer something `main()` knows about. Rewrote the middleware to be handlers mounted with the `any` verb. There's now a little code duplication in each of the proxying endpoints, but this does not yet hit my threshold for generalizing it. I do like that this approach let me hide all of the endpoint handlers inside their modules.
Additionally, removed all dependencies on native-tls from our usage of reqwest. In theory, this will make us more easily portable. In theory.
> Refactor the proxy mount routing extensively

- Cargo.lock
- agent/Cargo.toml
- agent/src/api/mod.rs
- agent/src/api/v1/jobs.rs
- agent/src/api/v1/proxy.rs
- agent/src/api/v1/storage.rs
- agent/src/main.rs
- utils/Cargo.toml
This commit adds the `metrics` crate, which is a commonly-used set of macros for emitting metrics used by many output generators, similar to the `log` and `tracing` crates. Typical metrics look like this:
```rust
metrics::increment_counter!("process:start");
metrics::histogram!("memory", someNumberHere);
metrics::increment_gauge!("gauge_name", someNumberHere);
```
This is literally all you need to do to send a new metric. The crate offers more affordances if you need them or want to re-use a specific metric emitter in a function.
Added basic metrics to each of the endpoints in the agent, as well as some process restart metrics.
Added one output sink, which we'll want to replace immediately because it's only suitable as a hello-world proof that metrics are being sent. In order to see …
> Start emitting metrics.

- Cargo.lock
- engine/Cargo.toml
- engine/src/lib.rs
- test-runner/src/main.rs
The [http-test](https://github.com/serval/wasm-samples/tree/main/http-test) sample app shows how to use this. You can try it with the test-runner like this:
````sh
$ echo https://whimsicalifornia.com/.beats | cargo run --bin test-runner ../wasm-samples/build/http-test.wasm
executing: ../wasm-samples/build/http-test.wasm
exit status: 0
stdout:
Fetching https://whimsicalifornia.com/.beats
Status code: 200
Headers:
- date: "Thu, 16 Mar 2023 19:28:13 GMT"
- server: "Apache"
- upgrade: "h2"
- connection: "Upgrade"
- cache-control: "max-age=172800"
- expires: "Sat, 18 Mar 2023 19:28:13 GMT"
- vary: "User-Agent"
- transfer-encoding: "chunked"
- content-type: "application/json"
Body:
{"beats":"852"}
stderr:
````
I had to fork the repository for the crate that implements this functionality so I …
> Support for making HTTP requests from WASM workloads

- Cargo.lock
- Cargo.toml
- agent/src/api/v1/jobs.rs
- agent/src/structures/mod.rs
- engine/src/errors.rs
- engine/src/extensions.rs
- engine/src/lib.rs
- test-runner/Cargo.toml
- test-runner/src/main.rs
- utils/Cargo.toml
- utils/src/errors.rs
- utils/src/structs.rs
This implements permission checks for jobs. I wanted to represent these in a nice format in the manifest files, so I ended up having to write my own serializing/deserializing code, which ended up taking up a lot more time than I expected. Alas. I think the format is pleasant:
- `proc:read:*` — whether they are allowed to read `/proc`; presumably a `proc:write:*` will make sense someday. Implementing more granular paths is an exercise for the future; my current thinking is that we'll have e.g. `proc:read:foo` to give access to `/proc/foo`, but maybe that's weird and we'll end up with a separate mechanism for giving access to various filesystem paths. Who knows!
- `extension:foo` — permission to use the extension `foo`
- `extension:*` — permission to use any extension
- `http:example.com` — …
> Job permissions

- engine/src/lib.rs
Per [the conversation in #dev yesterday](https://serval.slack.com/archives/C04BKH1J31S/p1679607830972129), wasmtime's compilation caching is off by default. Enabling it speeds up subsequent runs of the same .wasm file substantially (the ruby example goes from 15.5 seconds to around 0.4 seconds.
I also renamed the parameters to `ServalEngine::execute`, [per this comment](https://github.com/serval/serval-mesh/pull/46#discussion_r1145462026) from yesterday.
> Enable wasm caching

- Cargo.lock
- README.md
- agent/Cargo.toml
- agent/README.md
- agent/src/api/v1/jobs.rs
- agent/src/api/v1/proxy.rs
- agent/src/api/v1/storage.rs
- agent/src/main.rs
- agent/src/structures/mod.rs
- cli/Cargo.toml
- cli/src/main.rs
- engine/README.md
- engine/src/errors.rs
- engine/src/lib.rs
- engine/src/runtime/mod.rs
- queue/README.md
- test-runner/README.md
- test-runner/src/main.rs
- utils/Cargo.toml
- utils/src/lib.rs
- utils/src/mesh.rs
- utils/src/structs.rs
The agent and the cli now both attempt to join a network of peers, established via kaboodle, and use that network instead of mdns to discover relevant services. 
The most interesting implementation details are in the file `utils/src/mesh.rs`. This file includes some wrapper traits that probably belong in Kaboodle itself, since they were designed to be re-usable and to encode the responsibilities of any Kaboodle implementation: KaboodleMesh and KaboodlePeer. There are implementations plus some serval-specific functions in the structs ServalMesh and PeerMetadata. (All names are negotiable. I already don't like my initial choices.)
The peer metadata struct gets a little complicated because I attempted to provide some future-proofing via a way to version it. It's encoded via `binencode`, with …
> Switch from mdns to using the kaboodle peer mesh

- justfile
This adds a one-liner `just tailscale` to run serval-agent against your tailnet. It requires `crosswind` to be run separately, but is smart enough to notice when it should suggest that you run crosswind.
> 'just tailscale'

- Cargo.lock
- agent/src/api/v1/mesh.rs
- agent/src/api/v1/mod.rs
- agent/src/main.rs
- cli/Cargo.toml
- cli/src/main.rs
- cli/src/mesh.rs
- cli/src/peers.rs
- utils/Cargo.toml
- utils/src/mesh.rs
- utils/src/networking.rs
Three changes, two notable!
1. Added a new `monitor` command to the cli. This command joins the cli to the mesh as a `client` role, and prints out joins and leaves as it is informed of them.
The CLI and the agent both now respect a new env var: `MESH_INTERFACE`. If you don't provide one, kaboodle defaults to the best it can find. If you do provide a string here, we find an interface with a matching name. This allows me to specify ipv4 and therefore run tests successfully locally.
The CLI now only connects to a mesh to get a base url if it ever needs a base url. It doesn't need a base url for this command, for instance. This change caused a lot of trauma in the cli as things became async that were not previously so. tl;dr the CLI now uses `async_once_cell`.
Generalized some other things as …
> Mesh shenanigans in the CLI

- agent/src/main.rs
- cli/src/mesh.rs
- cli/src/peers.rs
- utils/src/mesh.rs
- utils/src/networking.rs
Lots of tiny commits here; sorry. Most of them are just cleaning up a handful of lines of code to be a bit more idiomatic.
The highlights:
- I pulled some chunks out of serval-agent's `main` function, creating a handful of `init_…()` functions just to give us a bit of containment
- I added an `INSTANCE_ID` environment variable to allow you to give a node a persistent identity
- KaboodlePeer - replace `Option<SocketAddr>` with `IpAddr` — this is explained extensively in the commit message
- Updated `HOST` and `METRICS_ADDR` to use IPv6 wildcards (`[::]`) by default rather than IPv4 (`0.0.0.0`). (`HOST` should probably be renamed; any suggestions for a better name?)
> ServalMesh grab bag

- .github/workflows/build.yaml
- .github/workflows/main.yaml
- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
Whipped up a [strongly-inspired-by-tomato](https://github.com/ceejbot/tomato/blob/v0.3.0/.github/workflows/build.yaml) build script. The main difference is using a matrix strategy to reduce the number of steps involved (no need to explicitly write out the build steps for amd64/arm64 separately).
The goal is to have a quick way to install Serval on machines without a Rust toolchain, which is beneficial for agents with low computing power (long build times) and for minimizing dependencies for running Serval in general.
> Build releases

- Cargo.lock
- agent/Cargo.toml
- agent/src/api/v1/storage.rs
- agent/src/storage/blobs.rs
- agent/src/storage/bucket.rs
- agent/src/storage/mod.rs
- api-client/src/lib.rs
- justfile
- utils/src/errors.rs
Added a layer of indirection to S3 storage as a cheap index. Instead of writing data to the user-provided key, we write an object containing the integrity hash for the data. We then create an object that contains the data using the integrity hash as a key. Re-implemented all data stores and fetches in the bucket via this indirection. This is of course invisible to clients of the storage layer.
Implemented `HEAD /v1/storage/data/*address` via `has_content_address()`, which is now possible that the bucket storage supports it.
The term sri is now gone from all API surfaces. Instead we use "integrity" as the word for this concept.
Improved some error reporting, and fixed a bug with how the cli reported hashes. (It was reporting hashes of the hashes instead of printing the hashes, because I …
> S3 buckets now support fetching content by address

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/src/main.rs
We no longer have colorized help. At some point we'll follow up with whatever clap settles on for styling help output.
> chore: update clap to 4

- justfile
Per https://serval.slack.com/archives/C04BKH1J31S/p1682721245996159
> 'just install-tools' should ensure that the nightly toolchain is installed
